### ISSUE TITLE
[Implementação] Criar novos adaptadores

### ISSUE THREAD

**Issue by ViiictorXD** [studae-project/Discord-Bot#11]
Inicialmente o projeto conta somente com 3 adaptadores, sendo eles:
`String` -> `StringAdapter.java`
`Boolean` ou `boolean` -> `BooleanAdapter.java`
`Context` -> `ContextAdapter.java`
Todos estão localizados no pacote `br.com.studae.commons.command.adapter.impl`.

É necessário a criação de outros adaptadores essenciais como: `Integer`, `Double`, `Long`, `User`, `Member`, `Role` e `TextChannel`.

**Comment by DavidNery** [comment]
Serão adicionados assim que terminarmos a revisão do #8
